import {useEffect,useMemo,useState} from 'react'
import {CalendarDays,Download,GraduationCap,Sparkles,Database,Layers3,Utensils} from 'lucide-react'
import {Mensa} from './mensa'
import type {CourseDatabase,CourseDatabaseStream,CourseDatabaseSubject,Meeting,Module,ScheduleData,Variant} from './types'
import {generateVariants,meetingsOverlap,minutes,pareto} from './lib/schedule'
import {examTracks,filterModules,groupTrackLabel,localDate,matchesTrack,meetingInWeek,sanitizeSettings,shiftDate,weekStart} from './lib/filters'
import type {Tracks} from './lib/filters'
import {exportICS,exportJSON} from './lib/export'
import {HomeworkList} from './homework'
import type {Task} from './homework'
import {formatDate} from './lib/text'
const assessmentLabel=(value:string)=>({exam:'Exam',hybrid:'Exam + coursework',project:'Project',coursework:'Coursework',unknown:'Not set'}[value]||value)
const classLabel=(value?:string)=>({lecture:'Lecture',exercise:'Practical session',project:'Project'}[value||'']||'Session')
const dayLabel=(value:string)=>DAYS.find(day=>day[0]===value)?.[1]||value
const DAYS=[['MO','Monday'],['TU','Tuesday'],['WE','Wednesday'],['TH','Thursday'],['FR','Friday']]
const COLORS=['#376f67','#c46b43','#6c63a8','#3676a8','#9a6b22','#527643','#a34f66','#386a82','#80634e']
type Tab='calendar'|'assignments'|'exams'|'data'|'combinations'|'mensa'
const tabs=[{id:'calendar',label:'Timetable',icon:CalendarDays},{id:'assignments',label:'Assignments',icon:Layers3},{id:'exams',label:'Exams',icon:GraduationCap},{id:'data',label:'Modules',icon:Database},{id:'mensa',label:'Canteen',icon:Utensils}] as const
const loadState=()=>{try{const value=JSON.parse(localStorage.getItem('bht-filters')||'{}');return value&&typeof value==='object'?value:{}}catch{return {}}}
const INITIAL_QUERY=new URLSearchParams(location.search)
const INITIAL_STATE=(()=>{const state=loadState();for(const [key,param] of [['enabled','modules'],['types','types'],['assessments','assessment']])if(INITIAL_QUERY.has(param))state[key]=INITIAL_QUERY.get(param)!.split(',').filter(Boolean);for(const [key,param] of [['teacher','teacher'],['teacherMode','teacherMode'],['parallelGroup','group']])if(INITIAL_QUERY.has(param))state[key]=INITIAL_QUERY.get(param);if(INITIAL_QUERY.has('zug')){state.zug=Number(INITIAL_QUERY.get('zug'));delete state.tracks}return state})()
function App(){
 const [homework,setHomework]=useState<Task[]>([]),[data,setData]=useState<ScheduleData|null>(null),[report,setReport]=useState<any>(null),[courseDb,setCourseDb]=useState<CourseDatabase|null>(null),[error,setError]=useState('')
 const initialTab=INITIAL_QUERY.get('tab')||INITIAL_STATE.tab
 const [tab,setTab]=useState<Tab>(tabs.some(t=>t.id===initialTab)?initialTab:'calendar')
 const [settings,setSettings]=useState(()=>sanitizeSettings(INITIAL_STATE,[],[]))
 const [priorities,setPriorities]=useState({days:INITIAL_STATE.priorities?.days!==false,gaps:INITIAL_STATE.priorities?.gaps!==false,early:INITIAL_STATE.priorities?.early===true,late:INITIAL_STATE.priorities?.late===true})
 const [week,setWeek]=useState(()=>weekStart(/^\d{4}-\d{2}-\d{2}$/.test(INITIAL_STATE.week||'')&&!isNaN(Date.parse(INITIAL_STATE.week))?INITIAL_STATE.week:localDate(new Date())))
 const [variants,setVariants]=useState<Variant[]>([]),[selected,setSelected]=useState<Variant|null>(null),[showAll,setShowAll]=useState(false)
 const change=(patch:Partial<typeof settings>)=>{setSettings(prev=>({...prev,...patch,...(patch.tracks||patch.enabled?{parallelGroup:'all'}:{})}));setSelected(null);setVariants([])}
 useEffect(()=>{Promise.all(['schedule','extraction-report','course-database','homework'].map(name=>fetch(`/data/${name}.json`).then(r=>{if(!r.ok)throw new Error('Data unavailable');return r.json()}))).then(([d,r,c,h])=>{setHomework(h.tasks);setData(d);setReport(r);setCourseDb(c);setSettings(sanitizeSettings(INITIAL_STATE,d.modules,d.teachers.map((t:any)=>t.teacherId)))}).catch(()=>setError('Could not load data. Reload to try again.'))},[])
 useEffect(()=>{if(!data)return;try{localStorage.setItem('bht-filters',JSON.stringify({...settings,priorities,week,tab:tab==='combinations'?'calendar':tab}))}catch{setError('Could not save preferences in this browser.')}const q=new URLSearchParams();q.set('tab',tab==='combinations'?'calendar':tab);history.replaceState(null,'',`?${q}`)},[data,settings,priorities,week,tab])
 const {enabled,tracks,teacher,teacherMode,parallelGroup,types,assessments}=settings
 const active=useMemo(()=>data?.modules.filter(m=>enabled.includes(m.moduleId)&&assessments.includes(m.assessment.classification))||[],[data,enabled,assessments])
 const filtered=useMemo(()=>filterModules(active,enabled,tracks,types,parallelGroup,teacher,teacherMode),[active,enabled,tracks,types,parallelGroup,teacher,teacherMode])
 const defaultMeetings=useMemo(()=>(selected?.meetings||filtered.flatMap(m=>m.courses.flatMap(c=>c.groups.flatMap(g=>g.meetings)))).filter(m=>meetingInWeek(m,week)),[filtered,selected,week])
 const conflicts=useMemo(()=>new Set(defaultMeetings.filter((a,i)=>defaultMeetings.some((b,j)=>i!==j&&meetingsOverlap(a,b))).map(m=>m.meetingId)),[defaultMeetings])
 if(!data)return <div className="loading">{error||'Loading…'}</div>
 const find=()=>{let all=generateVariants(filtered);all.sort((a,b)=>{if(teacher!=='all'&&teacherMode==='prefer'){const at=a.meetings.some(m=>m.teacherId===teacher),bt=b.meetings.some(m=>m.teacherId===teacher);if(at!==bt)return at?-1:1}if(priorities.early){const d=Number(a.metrics.earliest<'10:00')-Number(b.metrics.earliest<'10:00');if(d)return d}if(priorities.late){const d=Number(a.metrics.latest>'17:30')-Number(b.metrics.latest>'17:30');if(d)return d}return (priorities.days?a.metrics.days-b.metrics.days:0)||(priorities.gaps?a.metrics.gaps-b.metrics.gaps:0)});setVariants(showAll?all.slice(0,100):pareto(all));setTab('combinations')}
 const reset=()=>{change(sanitizeSettings({},data.modules,data.teachers.map(t=>t.teacherId)));setPriorities({days:true,gaps:true,early:false,late:false})}
 return <div className="app">
 <header><div className="brand"><CalendarDays size={22}/><div><b>Academic Planner</b><small>Timetable, assignments and assessments</small></div></div><div className="status">Updated · {formatDate(data.generatedAt)}</div></header>
 <nav>{tabs.map(t=><button className={tab===t.id||tab==='combinations'&&t.id==='calendar'?'active':''} onClick={()=>setTab(t.id)} key={t.id}><t.icon size={17}/>{t.label}</button>)}</nav>
 <div className="layout"><Sidebar data={data} settings={settings} change={change} priorities={priorities} setPriorities={setPriorities} showAll={showAll} setShowAll={setShowAll} reset={reset}/>
 <main>{error&&<p role="alert">{error}</p>}{tab==='calendar'&&<><div className="week-controls"><button aria-label="Previous week" onClick={()=>setWeek(shiftDate(week,-7))}>←</button><button onClick={()=>setWeek(weekStart(localDate(new Date())))}>Today</button><button aria-label="Next week" onClick={()=>setWeek(shiftDate(week,7))}>→</button><label>Go to date <input aria-label="Go to date" type="date" value={week} onChange={e=>{if(e.target.value)setWeek(weekStart(e.target.value))}}/></label><button onClick={find}><Sparkles size={14}/>Find schedule options</button></div><p className="active-settings">{selected?`Selected ${selected.id} · `:'All matching groups · '}{active.map(m=>`${m.name}: ${tracks[m.moduleId]==='all'?'all cohorts':`cohort ${tracks[m.moduleId]}`}`).join(' · ')} · {types.map(classLabel).join(', ')}{parallelGroup!=='all'?` · Group: ${data.modules.flatMap(m=>m.courses.flatMap(c=>c.groups)).find(g=>g.groupId===parallelGroup)?.parallelGroup??'unknown'}`:''}{teacher!=='all'?` · ${teacherMode}: ${data.teachers.find(t=>t.teacherId===teacher)?.name}`:''}{selected&&<button onClick={()=>setSelected(null)}>Clear option</button>}</p><Calendar data={data} meetings={defaultMeetings} conflicts={conflicts} selectedTeacher={teacher} week={week}/></>}
 {tab==='assignments'&&<div className="page"><HomeworkList modules={data.modules} imported={homework} enabled={active.map(m=>m.moduleId)} tracks={tracks}/></div>}
 {tab==='mensa'&&<Mensa week={week} setWeek={setWeek}/>}
 {tab==='combinations'&&<><button className="back" onClick={()=>setTab('calendar')}>← Timetable</button><Combinations items={variants} selected={selected} choose={v=>{setSelected(v);setTab('calendar')}} find={find}/></>}
 {tab==='exams'&&<Exams modules={active} tracks={tracks} courseDb={courseDb}/>}{tab==='data'&&<DataView data={data} report={report} courseDb={courseDb} enabled={active.map(m=>m.moduleId)} tracks={tracks}/>}</main></div></div>
}
function Sidebar({data,settings,change,priorities,setPriorities,showAll,setShowAll,reset}:any){const [modulesOpen,setModulesOpen]=useState(()=>window.innerWidth>850);useEffect(()=>{const resize=()=>setModulesOpen(window.innerWidth>850);window.addEventListener('resize',resize);return ()=>window.removeEventListener('resize',resize)},[]);const toggle=(arr:string[],v:string)=>arr.includes(v)?arr.filter(x=>x!==v):[...arr,v];return <aside><details className="module-filters" open={modulesOpen} onToggle={e=>setModulesOpen(e.currentTarget.open)}><summary>Modules and cohorts</summary><div className="module-filter-list">{data.modules.map((m:Module)=><div className="module-filter" key={m.moduleId}><label className="check"><input type="checkbox" checked={settings.enabled.includes(m.moduleId)} onChange={()=>change({enabled:toggle(settings.enabled,m.moduleId)})}/>{m.name}</label><select aria-label={`${m.name} cohort`} value={settings.tracks[m.moduleId]||'all'} onChange={e=>change({tracks:{...settings.tracks,[m.moduleId]:e.target.value==='all'?'all':Number(e.target.value)}})}><option value="all">All cohorts</option>{[...new Set(m.courses.flatMap(c=>c.groups.flatMap(g=>g.zugs)))].sort().map(z=><option key={z} value={z}>Cohort {z}</option>)}</select></div>)}</div></details>
 <details><summary>Additional filters and preferences</summary><section className="filters"><label>Instructor</label><select value={settings.teacher} onChange={e=>change({teacher:e.target.value})}><option value="all">All instructors</option>{data.teachers.map((t:any)=><option value={t.teacherId} key={t.teacherId}>{t.name}</option>)}</select>{settings.teacher!=='all'&&<select aria-label="Instructor mode" value={settings.teacherMode} onChange={e=>change({teacherMode:e.target.value})}>{['highlight','prefer','exclude'].map(v=><option key={v} value={v}>{v}</option>)}</select>}
 <label>Group</label><select value={settings.parallelGroup} onChange={e=>change({parallelGroup:e.target.value})}><option value="all">All groups</option>{data.modules.filter((m:Module)=>settings.enabled.includes(m.moduleId)).flatMap((m:Module)=>m.courses.flatMap(c=>c.groups.filter(g=>matchesTrack(g.zugs,settings.tracks[m.moduleId])).map(g=><option key={g.groupId} value={g.groupId}>{m.name} · {classLabel(c.type)} · Group {g.parallelGroup??'unknown'}</option>)))}</select>
 <label>Session type</label><div className="chips">{['lecture','exercise','project'].map(v=><button key={v} className={settings.types.includes(v)?'active':''} onClick={()=>change({types:toggle(settings.types,v)})}>{classLabel(v)}</button>)}</div>
 <label>Assessment</label><div className="chips">{['exam','hybrid','project','coursework','unknown'].map(v=><button key={v} className={settings.assessments.includes(v)?'active':''} onClick={()=>change({assessments:toggle(settings.assessments,v)})}>{assessmentLabel(v)}</button>)}</div></section>
 <section><label>Option preferences</label>{[['days','Fewer days'],['gaps','Fewer gaps'],['early','Start after 10:00'],['late','End before 17:30']].map(([k,l])=><label className="check" key={k}><input type="checkbox" checked={priorities[k]} onChange={()=>setPriorities({...priorities,[k]:!priorities[k]})}/>{l}</label>)}<label className="check"><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/>All options</label></section></details><button className="reset" onClick={reset}>Reset filters</button></aside>}
function Calendar({data,meetings,conflicts,selectedTeacher,week}:{week:string;data:ScheduleData;meetings:Meeting[];conflicts:Set<string>;selectedTeacher:string}){const color=(id:string)=>COLORS[data.modules.findIndex(m=>m.moduleId===id)%COLORS.length];return <div className="page"><div className="headline"><div><h1>Timetable</h1><p>Mon–Fri · 08:00–21:00 · {meetings.length} sessions</p></div><div className="legend"><i className="lecture"></i>Lecture <i className="exercise"></i>Practical session</div></div>
 <div className="calendar"><div className="times"><b></b>{Array.from({length:14},(_,i)=><span key={i}>{String(i+8).padStart(2,'0')}:00</span>)}</div>{DAYS.map(([key,name])=><div className="day" key={key}><div className="day-head"><b>{name}<small>{formatDate(shiftDate(week,DAYS.findIndex(d=>d[0]===key)))}</small></b><span>{meetings.filter(m=>m.weekday===key).length} sessions</span></div><div className="day-grid">{Array.from({length:13},(_,i)=><i style={{top:`${i/13*100}%`}} key={i}></i>)}{meetings.filter(m=>m.weekday===key).sort((a,b)=>a.start.localeCompare(b.start)).map(m=>{const mod=data.modules.find(x=>x.moduleId===m.moduleId)!;const course=mod.courses.find(c=>c.courseId===m.courseId);const group=course?.groups.find(g=>g.groupId===m.groupId);return <article key={m.meetingId} className={`${course?.type} ${conflicts.has(m.meetingId)?'conflict':''} ${selectedTeacher!=='all'&&m.teacherId===selectedTeacher?'teacher-focus':''}`} style={{top:`${(minutes(m.start)-480)/780*100}%`,height:`${(minutes(m.end)-minutes(m.start))/780*100}%`,borderLeftColor:color(m.moduleId),background:`color-mix(in srgb, ${color(m.moduleId)} 12%, white)`}} title={`${formatDate(m.dateStart)} — ${formatDate(m.dateEnd)}\nSource: ${m.source.sourceFile}\n${m.source.fragment}`}><div><b>{m.start}–{m.end}</b><em>{classLabel(course?.type)}</em></div><strong>{mod.name}</strong><small>{group?groupTrackLabel(group):'Cohort not specified'} · Group {group?.parallelGroup??'unknown'}</small><small>{m.teacher.replace('Prof. Dr. ','')}</small><small>{m.room}</small></article>})}</div></div>)}</div>
 <div className="mobile-days">{DAYS.map(([key,name])=><section key={key}><h3>{name} · {formatDate(shiftDate(week,DAYS.findIndex(d=>d[0]===key)))}</h3>{meetings.filter(m=>m.weekday===key).sort((a,b)=>a.start.localeCompare(b.start)).map(m=><div className="mobile-event" key={m.meetingId}><b>{m.start}</b><span>{data.modules.find(x=>x.moduleId===m.moduleId)?.name}<small>{m.start}–{m.end} · {classLabel(data.modules.find(x=>x.moduleId===m.moduleId)?.courses.find(c=>c.courseId===m.courseId)?.type)} · {data.modules.flatMap(x=>x.courses.flatMap(c=>c.groups)).filter(g=>g.groupId===m.groupId).map(g=>`${groupTrackLabel(g)} · Group ${g.parallelGroup??'unknown'}`).join('')} · {m.teacher} · {m.room}</small></span></div>)}</section>)}</div>
 </div>}

function Combinations({items,selected,choose,find}:{items:Variant[];selected:Variant|null;choose:(v:Variant)=>void;find:()=>void}){return <div className="page"><div className="headline"><div><h1>Schedule options</h1><p>Options use the active filters and have no overlapping sessions. Search keeps up to 5,000 partial options at each step; results are not exhaustive.</p></div></div>{!items.length?<div className="empty"><Sparkles/><h2>No matching options</h2><p>Adjust the active filters and try again.</p><button className="primary" onClick={find}>Find options</button></div>:<div className="variants">{items.map((v,i)=><article className={selected?.id===v.id?'selected':''} key={v.id}><div className="rank">#{i+1}</div><div className="variant-main"><h3>Option {i+1}</h3><p>{v.reasons.join(' · ')}</p><div className="metric-row"><Metric n={v.metrics.days} t="Attendance days"/><Metric n={`${Math.round(v.metrics.minutes/60)} h`} t="Contact hours"/><Metric n={`${v.metrics.gaps} min`} t="Gaps"/><Metric n={v.metrics.buildingChanges} t="Building changes"/><Metric n={v.metrics.teachers} t="Instructors"/></div><div className="group-list">{v.groups.map(g=><span key={g.groupId}>{g.titleOriginal.replace(' Übg.','')} · Group {g.parallelGroup??'unknown'}</span>)}</div></div><div className="variant-actions"><button onClick={()=>choose(v)}>Show timetable</button><button onClick={()=>exportJSON(v)}><Download size={14}/> JSON</button><button onClick={()=>exportICS(v)}><CalendarDays size={14}/> ICS</button></div></article>)}</div>}</div>}
function Metric({n,t}:{n:any;t:string}){return <div><b>{n}</b><small>{t}</small></div>}

function Exams({modules,tracks,courseDb}:{modules:Module[];tracks:Tracks;courseDb:CourseDatabase|null}){
 const exams=modules.flatMap(m=>m.examSlots.filter(e=>matchesTrack(examTracks(m,e),tracks[m.moduleId])).map(e=>({id:e.examSlotId,date:e.date||'',title:m.name,time:e.start?`${e.start}–${e.end}`:'',detail:`${examTracks(m,e).length>1?`Shared · Cohorts ${examTracks(m,e).join(', ')}`:examTracks(m,e).length?`Cohort ${examTracks(m,e)[0]}`:'Cohort not specified'} · Exam group ${e.parallelGroup} · Session group ${e.gvParallelGroup} · ${e.examiner}`,source:e.source})))
 const deadlines=(courseDb?.subjects||[]).filter(s=>modules.some(m=>m.moduleId===s.moduleId)).flatMap(s=>s.streams.filter(stream=>matchesTrack([stream.zug],tracks[s.moduleId])).flatMap(stream=>(stream.details?.deadlines||[]).map((d:any)=>({id:`${s.moduleId}-${stream.zug}-${d.date}-${d.label}`,date:d.date||'',title:`${s.name} · ${d.label}`,time:'',detail:`Deadline · Cohort ${stream.zug}`,source:null}))).concat((s.unassignedDetails?.deadlines||[]).map(d=>({id:`${s.moduleId}-unknown-${d.date}-${d.label}`,date:d.date||'',title:`${s.name} · ${d.label}`,time:'',detail:'Deadline · Cohort not specified',source:null}))))
 const rows=[...exams,...deadlines].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')||a.title.localeCompare(b.title))
 let month='',date=''
 return <div className="page"><div className="headline"><div><h1>Exams and deadlines</h1><p>Unknown cohorts remain visible. Dates follow the available sources.</p></div></div>{!rows.length&&<p>No dates to show.</p>}<div className="date-list">{rows.map(row=>{const bucket=row.date.slice(0,7)||'No date set',newMonth=bucket!==month,newDate=row.date!==date;month=bucket;date=row.date;return <div key={row.id}>{newMonth&&<h2>{row.date?new Date(row.date+'T12:00').toLocaleDateString('en-GB',{month:'long',year:'numeric'}):bucket}</h2>}{newDate&&row.date&&<h3>{formatDate(row.date)}</h3>}<article title={row.source?`${row.source.sourceFile} · ${row.source.fragment}`:undefined}><time>{row.time||(row.detail.startsWith('Deadline')?'—':'By arrangement')}</time><div><b>{row.title}</b><small>{row.detail}</small></div></article></div>})}</div></div>
}

function DataView({data,report,courseDb,enabled,tracks}:{data:ScheduleData;report:any;courseDb:CourseDatabase|null;enabled:string[];tracks:Tracks}){return <div className="page"><div className="headline"><div><h1>Modules</h1><p>{courseDb?`${courseDb.coverage.subjects} modules · ${courseDb.coverage.streams} cohorts · ${courseDb.coverage.enrichedStreams} cohorts with details`:'Loading…'}</p></div></div>{courseDb?<div className="course-db">{courseDb.subjects.filter(s=>enabled.includes(s.moduleId)).map(subject=><SubjectRecord subject={{...subject,streams:subject.streams.filter(stream=>matchesTrack([stream.zug],tracks[subject.moduleId]))}} key={subject.moduleId}/>)}</div>:null}<ModuleDiagnostics modules={filterModules(data.modules,enabled,tracks,['lecture','exercise','project'],'all','all','highlight')}/><details><summary>Import details</summary><p>{report?.counts?.modules} modules · {report?.counts?.courses} courses · {report?.counts?.groups} groups · {report?.counts?.meetings} sessions · {report?.counts?.examSlots} exams</p><p>{report?.warnings?.length||0} warnings · {report?.unresolvedFields?.reduce((total:number,field:any)=>total+field.count,0)||0} missing values</p></details></div>}

function ModuleDiagnostics({modules}:{modules:Module[]}){
 const meetings=modules.flatMap(m=>m.courses.flatMap(c=>c.groups.flatMap(g=>g.meetings)))
 const overlaps=meetings.flatMap((a,i)=>meetings.slice(i+1).filter(b=>meetingsOverlap(a,b)).map(b=>({a,b})))
 const shared=overlaps.filter(({a,b})=>a.teacherId===b.teacherId||a.room===b.room)
 const exams=modules.flatMap(m=>m.examSlots).filter(e=>e.date).sort((a,b)=>a.date!.localeCompare(b.date!))
 const nearby=exams.flatMap((a,i)=>exams.slice(i+1).filter(b=>a.moduleId!==b.moduleId&&(+new Date(b.date!)-+new Date(a.date!))/86400000<=7).map(b=>({a,b})))
 return <details><summary>Schedule diagnostics</summary><p>{overlaps.filter(({a,b})=>a.moduleId!==b.moduleId).length} possible overlaps between modules · {shared.length} instructor / room overlaps · {nearby.length} pairs of exams within 7 days</p>{shared.map(({a,b},i)=><p key={i}>{dayLabel(a.weekday)} {a.start} · {a.teacherId===b.teacherId?a.teacher:a.room} · {modules.find(m=>m.moduleId===a.moduleId)?.name} / {modules.find(m=>m.moduleId===b.moduleId)?.name}</p>)}{nearby.map(({a,b},i)=><p key={`exam-${i}`}>{formatDate(a.date)} – {formatDate(b.date)} · {modules.find(m=>m.moduleId===a.moduleId)?.name} / {modules.find(m=>m.moduleId===b.moduleId)?.name}</p>)}</details>
}

function SubjectRecord({subject}:{subject:CourseDatabaseSubject}){const baseline=subject.assessmentBaseline.components.map(x=>`${x.percent}% ${x.label}`).join(' + ');return <article className="subject-record"><header><div><h2>{subject.name}</h2><p>{subject.modulNumber} · Semester {subject.semester} · {subject.credits} credits</p></div><mark className={subject.assessmentBaseline.classification}>{assessmentLabel(subject.assessmentBaseline.classification)}</mark></header><div className="subject-baseline"><b>Handbook assessment:</b> {baseline}{subject.assessmentBaseline.examDurationMinutes?` · ${subject.assessmentBaseline.examDurationMinutes} minutes`:''}<small>{subject.workload}</small></div>{subject.streams.length?<div className="stream-grid">{subject.streams.map(stream=><StreamRecord stream={stream} key={stream.zug}/>)}</div>:null}{subject.unassignedDetails?<section className="stream-record"><h3>Cohort not specified</h3>{subject.unassignedDetails.keyFacts.map(fact=><small className="key-fact" key={fact}>{fact}</small>)}{subject.unassignedDetails.workloadRules?.map(rule=><small className="key-fact" key={rule}>{rule}</small>)}{subject.unassignedDetails.deadlines.map(deadline=><small className="deadline" key={deadline.date}><b>{formatDate(deadline.date)}</b> — {deadline.label}</small>)}</section>:null}{subject.projectGroups?<div className="project-summary"><b>Project groups</b><p>{subject.projectGroups.offered.join(', ')}</p><small>Assigned: {subject.projectGroups.signupSnapshot.assigned} of {subject.projectGroups.signupSnapshot.studentsTotal}. No group: {subject.projectGroups.signupSnapshot.unassigned}. Examiners: {subject.projectGroups.examiners.join(', ')}.</small><small>{subject.projectGroups.privacyNote}</small></div>:null}</article>}

function StreamRecord({stream}:{stream:CourseDatabaseStream}){const d=stream.details;return <section className={`stream-record ${d?'enriched':''}`}><div className="stream-title"><h3>Cohort {stream.zug}</h3><span>{d?'Course details':'Timetable and handbook'}</span></div><p><b>Instructors:</b> {stream.teachers.join(', ')}</p><div className="stream-times">{stream.courses.map(course=><small key={`${course.courseId}-${course.parallelGroup}`}><b>{classLabel(course.type)} · Group {course.parallelGroup??'unknown'}</b> — {course.meetings.map(m=>`${dayLabel(m.weekday)} ${m.start}–${m.end}, ${m.room}`).join(' · ')}</small>)}</div>{d?.actualAssessment?<div className="actual-rules"><b>Course assessment</b><p>{d.actualAssessment.components.map((x:any)=>`${x.percent}% ${x.label}`).join(' + ')}</p>{d.actualAssessment.passConditions?.map((x:string)=><small key={x}>{x}</small>)}</div>:null}{d?.exerciseAssessment?<div className="actual-rules"><b>Practical assessment</b><p>{d.exerciseAssessment.assignments} assignments · {d.exerciseAssessment.milestonesPerAssignment} milestones each · {d.exerciseAssessment.learningChecksPerAssignment} learning checks</p><small>{d.exerciseAssessment.points}</small>{d.exerciseAssessment.passConditions?.map((x:string)=><small key={x}>{x}</small>)}</div>:null}{d?.keyFacts?.map((x:string)=><small className="key-fact" key={x}>{x}</small>)}{d?.workloadRules?.slice(0,4).map((x:string)=><small className="key-fact" key={x}>{x}</small>)}{d?.deadlines?.map((x:any)=><small className="deadline" key={`${x.date}-${x.label}`}><b>{formatDate(x.date)}</b> — {x.label}</small>)}</section>}

export default App
