export type CourseType = 'lecture' | 'exercise' | 'project'
export interface SourceRef { sourceFile:string; fragment:string }
export interface Meeting { meetingId:string; groupId:string; moduleId:string; courseId:string; teacherId:string; teacher:string; room:string; weekday:string; dateStart:string|null; dateEnd:string|null; start:string; end:string; source:SourceRef }
export interface Group { groupId:string; courseId:string; moduleId:string; parallelGroup:number|null; titleOriginal:string; zugs:number[]; teacherId:string; teacher:string; registrationPeriod:string|null; meetings:Meeting[]; source:SourceRef }
export interface Course { courseId:string; moduleId:string; veranstaltungNumber:string; title:string; titleOriginal:string; type:CourseType; groups:Group[]; source:SourceRef }
export interface ExamSlot { zugs?:number[]; room?:string; examSlotId:string; moduleId:string; courseId:string; parallelGroup:number; gvParallelGroup:number; teacherId:string; examiner:string; nachVereinbarung:boolean; date:string|null; weekday:string|null; start:string|null; end:string|null; source:SourceRef }
export interface Module { moduleId:string; sourceCode:string; name:string; originalName:string; modulNumber:string; semester:number; credits:number; status:string; progressStatus:string; unscheduled:boolean; workload:string; teachingForm:string; assessment:{classification:'exam'|'project'|'hybrid'|'coursework'|'unknown';components:{label:string;percent:number}[];examDurationMinutes:number|null;courseworkScope:string|null;assessmentRaw:string;note:string;source:SourceRef};courses:Course[];examSlots:ExamSlot[];source:SourceRef }
export interface ScheduleData { schemaVersion:number;term:string;generatedAt:string;modules:Module[];meetings:Meeting[];examSlots:ExamSlot[];teachers:{teacherId:string;name:string}[] }
export interface CourseDatabaseStream { zug:number;teachers:string[];courses:{courseId:string;type:CourseType;parallelGroup:number|null;teacher:string;registrationPeriod:string|null;meetings:{weekday:string;start:string;end:string;room:string;dateStart:string|null;dateEnd:string|null}[]}[];detailStatus:'enriched'|'schedule_and_module_handbook_only';details:any|null }
export interface CourseDatabaseSubject { moduleId:string;modulNumber:string;name:string;semester:number;credits:number;status:string;workload:string;teachingForm:string;assessmentBaseline:Module['assessment'];streams:CourseDatabaseStream[];unassignedDetails?:{scope:string;keyFacts:string[];workloadRules?:string[];deadlines:{date:string;label:string;mandatory?:boolean}[];sources:SourceRef[]};projectGroups?:{offered:string[];signupSnapshot:{studentsTotal:number;assigned:number;unassigned:number;countsByProject:Record<string,number>};examiners:string[];privacyNote:string;sources:SourceRef[]} }
export interface CourseDatabase { schemaVersion:number;term:string;generatedAt:string;description:string;coverage:{subjects:number;streams:number;enrichedStreams:number};subjects:CourseDatabaseSubject[] }
export interface Variant { id:string; groups:Group[]; meetings:Meeting[]; metrics:{days:number;minutes:number;gaps:number;earliest:string;latest:string;buildingChanges:number;conflicts:number;teachers:number}; reasons:string[] }
